### ISSUE TITLE
Set IdleTimeout on Tyrus?

### ISSUE THREAD

**Issue by cinterloper** [SUSE/saltstack-netapi-client-java#132]
there is a very short default idle timeout on the websocket container when using Tyrus:
(Java)
 got event: salt/job/20151026074505629209/ret/balthazarServer
 with data:
 [fun_args:[], jid:20151026074505629209, return:[datasets:[NAME          USED  AVAIL  REFER  MOUNTPOINT, core         6.58M  7.81T  5.73M  /core, core/docker   170K  7.81T   170K  /var/lib/docker]], retcode:0.0, success:true, cmd:_return, _stamp:2015-10-26T07:45:06.291380, fun:zfs.list, id:balthazarServer]

saltReactor stream closed

(salt master api log) 
2015-10-26 07:52:19,224 [ws4py            ][DEBUG   ][40] Closing message received (1000) '"Session closed by the container because of the idle timeout."'
2015-10-26 07:52:19,225 [ws4py            ][INFO    ][40] Terminating websocket [Local => 172.17.0.74:8000 | Remote => 172.17.42.1:43364]

I believe this is configurable:
https://tyrus.java.net/apidocs/1.3/javax/websocket/WebSocketContainer.html#setDefaultMaxSessionIdleTimeout(long)

but all the config objects seem to be private.... how do i pass a custom config with a long timeout?

**Comment by lucidd** [comment]
Hi the timeout should be configurable via the `ClientConfig` like so.

`client.getConfig().put(ClientConfig.SOCKET_TIMEOUT, 0)`

**Comment by cinterloper** [comment]
Ah, i was going about it wrong, i was trying to get client.events() then set it, and i was also trying to do new EventStream(cfg,listener), which appears to be possiable in the master branch, but not in .6 just EventStream(cfg).addEventListener(listener)
https://github.com/cinterloper/saltstack-netapi-client-java/blob/master/src/main/java/com/suse/saltstack/netapi/event/EventStream.java#L78

anyway, its working for me now 

cfg = client.getConfig()
cfg.put(ClientConfig.SOCKET_TIMEOUT , 0)
...

     EventListener sr = (new saltReactor(vertx,""))

     es = new EventStream(cfg)
     es.addEventListener(sr)

**Comment by lucidd** [comment]
After you set the timeout int he ClientConfig the eventStream returned by `client.events()` will also have the timeout.
