### ISSUE TITLE
Issues with tests

### ISSUE THREAD

**Issue by lucidd** [SUSE/saltstack-netapi-client-java#43]
While working on #42 i found a few problems that i want to discuss and get some feedback first before changing anything. 

#### `testLoginFailure`

I'm not completely sure what [testLoginFailure](https://github.com/SUSE/saltstack-netapi-client-java/blob/master/src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java#L72-L80) tests. From what i can tell i would say it was supposed to test logging in with wrong credentials but since it throws the exception for all return codes other than `OK` and `ACCEPTED` this test passes in a lot of cases when it shouldn't.

Of course we could check if the exception message contains the right error code but i think it would be better to not leak the HTTP return codes and instead throw more meaningful exceptions so it is easier to handle different errors differently.

#### `stubFor` vs `verify`

Wiremock allows to specify matching rules in both `stubFor` and `verify`. While `stubFor`
is basically a router to determine which requests get served what response, verify serves the role of an assertion for the test. The problem is when a request does not match the `stubFor` it gets served a `404` which results in the test failing with a `SaltStackException` containing the `404`. There is not a lot of information about what went wrong. On the other hand if a request does not match the `verify` rules both expected and actual request(s) are printed as part of the failure.

So my suggestion would be using a `stubFor` that accepts all requests and shifting the the verification completely to verify.

**Comment by moio** [comment]
Your points make sense to me. Feel free to proceed fixing them (in case they are still relevant), otherwise let's simply keep this issue open not to forget about it.

Thanks

**Comment by lucidd** [comment]
It should be still relevant. I will prepare a PR as soon as i have some time.

**Comment by lucidd** [comment]
Fixed by #66
