### ISSUE TITLE
Run checkstyle on test classes

### ISSUE THREAD

**Issue by renner** [SUSE/saltstack-netapi-client-java#52]
When looking at [SaltStackClientTest.java] (https://github.com/SUSE/saltstack-netapi-client-java/blob/master/src/test/java/com/suse/saltstack/netapi/client/SaltStackClientTest.java) it seems that we do not run checkstyle on the test classes, there is long lines and star imports.

**Comment by hustodemon** [comment]
will take a look at it tomorrow.

**Comment by lucidd** [comment]
@hustodemon setting `includeTestSourceDirectory` to true works there are quite a few violations to fix. I will submit a PR so you can focus on getting #45 merged if that's ok for you :)

**Comment by hustodemon** [comment]
No probs, as soon as this is merged, I'll rebase #45. Thanks!
