### ISSUE TITLE
Travis could generate and publish javadocs with every build

### ISSUE THREAD

**Issue by renner** [SUSE/saltstack-netapi-client-java#68]
Travis could generate javadocs with every build, at least as long as it is the master branch that's being built. An always up to date development version of the javadocs can then be automatically pushed to github pages I guess. Note that the current [v0.1.0 javadocs] (http://suse.github.io/saltstack-netapi-client-java/apidocs/) were pushed manually.

How others are doing this:
- http://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/
- https://github.com/Jasig/cas/blob/master/travis/push-javadoc-to-gh-pages.sh

**Comment by lucidd** [comment]
Fixed by #69
