### ISSUE TITLE
Use TypeAdapter over JsonDeserializer

### ISSUE THREAD

**Issue by renner** [SUSE/saltstack-netapi-client-java#75]
[Gson Javadoc for `JsonDeserializer`] (https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/JsonDeserializer.html) says: "New applications should prefer TypeAdapter, whose streaming API is more efficient than this interface's tree API". We still have some implementations of `JsonDeserializer` in the `JsonParser` class that should be converted, namely:

- `StatsDeserializer`
- `ArgumentsDeserializer`

**Comment by hustodemon** [comment]
(We should bear in mind that `JsonDeserializer` is null-safe by default (according to my research it uses null-safe `TreeTypeAdapter` internally).)

**Comment by wallner** [comment]
I would like to try my hand on this, is this still being worked on? If not I would like to have a got at it this week.

**Comment by lucidd** [comment]
@wallner I'm not aware of anyone actively working on this issue so feel free to take it on. PRs are always welcome :smile:

**Comment by renner** [comment]
There is no `JsonDeserializer` implementations left after the merge of #124. Thanks for the patch @mathall! Closing this issue.
