### ISSUE TITLE
Can you post this to maven repository?

### ISSUE THREAD

**Issue by 0312birdzhang** [SUSE/saltstack-netapi-client-java#80]
:smile:

**Comment by 0312birdzhang** [comment]
I'm sorry , search "saltstack" can found,but "salt" not :joy:

**Comment by renner** [comment]
Hello @0312birdzhang, we will make the library available via the maven central repository (if that is what you mean), but unfortunately we are not completely there yet. We are tracking this with #72.

In the meantime please download the jar from the [releases] (https://github.com/SUSE/saltstack-netapi-client-java/releases).

**Comment by 0312birdzhang** [comment]
@renner yeah,i mean this. Thank you.
