### ISSUE TITLE
Support expr_form

### ISSUE THREAD

**Issue by mchugh19** [SUSE/saltstack-netapi-client-java#82]
The SaltAPI allows for setting a expr_form option which modifies what is selected by tgt. 
http://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.cmd

By default glob is used, and it would nice to be able to select others such as nodegroup.

**Comment by mchugh19** [comment]
It appears that expr_form is not currently able to be set via the existing methods. Here are some examples of the json the SaltAPI can use:

The default glob method
```json
[{
    "arg": ["echo testing"],
    "client": "local",
    "expr_form": "glob",
    "fun": "cmd.run",
    "tgt": "dynocache2*"
}]
```

List
```json
[{
    "arg": ["echo testing"],
    "client": "local",
    "expr_form": "list",
    "fun": "cmd.run",
    "tgt": ["dynocache2v1.cws.dpdcn.unt.edu", "dynocache2v2.cws.dpdcn.unt.edu"]
}]
```

Nodegroup
```json
[{
    "arg": ["echo testing"],
    "client": "local",
    "expr_form": "nodegroup",
    "fun": "cmd.run",
    "tgt": "webserver"
}]
```

**Comment by lucidd** [comment]
Thank you for reporting this and for providing the examples. I just tested the `expr_form` on my local setup and it seems to work find for the `/minions` and the `/run` endpoint. We will definitely include a way to make use of this in the future.  If there is any other feature that you feel is missing from this library feel free to let us know. :smile:

**Comment by lucidd** [comment]
This got addressed by https://github.com/SUSE/saltstack-netapi-client-java/pull/88

**Comment by mchugh19** [comment]
Hey all. 

The expr_form functionality is looking good. But it looks like not all are supported. https://docs.saltstack.com/en/latest/ref/clients/ shows the api and it looks like we're missing: 
pcre - Perl style regular expression
grain - Match based on a grain comparison
grain_pcre - Grain comparison with a regex
pillar - Pillar data comparison
pillar_pcre - Pillar data comparison with a regex
range - Use a Range server for matching
compound - Pass a compound match string

**Comment by lucidd** [comment]
Hey thanks for the feedback. I opened a separate [issue](https://github.com/SUSE/saltstack-netapi-client-java/issues/103) to keep track the progress of `expr_form`. If there is any particular `expr_form` that you need the most just comment on that issue and let us know so we can prioritize that.

**Comment by mcalmer** [comment]
Seems that `expr_form` is deprecated and must be replaced very soon:

```
DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluorine.
```

salt is currently at `Oxygen` release and `Fluorine` will be the next one.
