### ISSUE TITLE
Refactor the main class

### ISSUE THREAD

**Issue by renner** [SUSE/saltstack-netapi-client-java#99]
The main library class (`SaltStackClient.java`) has grown quite a bit, especially since the recent merge of #94. It could make sense to refactor this class now, moving away the new methods (`callSync()` and `callAsync()`) into a separate *module* of the library for instance.

**Comment by AdamMajer** [comment]
Can you clarify term *module*?

The `callSync()` and `callAsync()` members could be moved as member functions of `calls` package taking `SaltStackClient` as parameter. So for example, `WheelCall.java` would have a `callSync(SaltStackClient client)` and similar async function.

**Comment by renner** [comment]
Sorry for the late reply, I mean a separate class, while leaving it open how this should be designed. What would be important to me is that we create a nice API for the users of the library that allows to write beautiful and readable code. Thanks for your pull request, I will have a look and give feedback there.

**Comment by renner** [comment]
Closing this issue after the merge of #120.
